CREATE TABLE comment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id   BIGINT        NOT NULL,
    author      VARCHAR(100)  NOT NULL,
    body        VARCHAR(2000) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_comment_ticket FOREIGN KEY (ticket_id) REFERENCES ticket (id)
);

CREATE INDEX idx_comment_ticket_id ON comment (ticket_id, created_at);
