CREATE TABLE ticket_status_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id   BIGINT        NOT NULL,
    from_status VARCHAR(20),
    to_status   VARCHAR(20)   NOT NULL,
    changed_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    note        VARCHAR(2000),
    CONSTRAINT fk_history_ticket FOREIGN KEY (ticket_id) REFERENCES ticket (id)
);

CREATE INDEX idx_history_ticket_id ON ticket_status_history (ticket_id, changed_at);
